///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Web_DashBoard.Record_Actions.Page
{
    public partial class SelectPage
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void NavigateToPage(string modSelectedPageName, RepoItemInfo webdocumentInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click Page '$modSelectedPageName'.");
        	ATag btnSelectedPage = "//div[#'main-menu']//a[@innertext= '" + modSelectedPageName + "']";
           	btnSelectedPage.Click();
           	
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Caption' to contain the specified value $modSelectedPageName. Associated repository item: 'webdocumentInfo'", webdocumentInfo);
            webdocumentInfo.WaitForAttributeContains(5000, "Caption", modSelectedPageName);
        }
    }
}
