///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Web_DashBoard
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Web_DashBoardRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c0b288b1-adc9-4642-a32e-5641551c150e")]
    public partial class Web_DashBoardRepository : RepoGenBaseFolder
    {
        static Web_DashBoardRepository instance = new Web_DashBoardRepository();
        Web_DashBoardRepositoryFolders.DashboardAppFolder _dashboard;
        Web_DashBoardRepositoryFolders.PopupAppFolder _popup;

        /// <summary>
        /// Gets the singleton class instance representing the Web_DashBoardRepository element repository.
        /// </summary>
        [RepositoryFolder("c0b288b1-adc9-4642-a32e-5641551c150e")]
        public static Web_DashBoardRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Web_DashBoardRepository() 
            : base("Web_DashBoardRepository", "/", null, 0, false, "c0b288b1-adc9-4642-a32e-5641551c150e", ".\\RepositoryImages\\Web_DashBoardRepositoryc0b288b1.rximgres")
        {
            _dashboard = new Web_DashBoardRepositoryFolders.DashboardAppFolder(this);
            _popup = new Web_DashBoardRepositoryFolders.PopupAppFolder(this);
        }

#region Variables

        string _modSelectedItem = "";

        /// <summary>
        /// Gets or sets the value of variable modSelectedItem.
        /// </summary>
        [TestVariable("0b52e6cb-f81d-49cd-94fc-37ca34305381")]
        public string modSelectedItem
        {
            get { return _modSelectedItem; }
            set { _modSelectedItem = value; }
        }

        string _modValidateNotExistPageName = "";

        /// <summary>
        /// Gets or sets the value of variable modValidateNotExistPageName.
        /// </summary>
        [TestVariable("e92a8d07-3b39-4648-8de0-d9d309b59f2e")]
        public string modValidateNotExistPageName
        {
            get { return _modValidateNotExistPageName; }
            set { _modValidateNotExistPageName = value; }
        }

        string _repoPageName = "";

        /// <summary>
        /// Gets or sets the value of variable repoPageName.
        /// </summary>
        [TestVariable("643b0c28-4bc5-4754-ac40-9a1ef660178f")]
        public string repoPageName
        {
            get { return _repoPageName; }
            set { _repoPageName = value; }
        }

        string _repoSelectedItem = "";

        /// <summary>
        /// Gets or sets the value of variable repoSelectedItem.
        /// </summary>
        [TestVariable("26955889-fa67-4888-819b-fd4a9830099a")]
        public string repoSelectedItem
        {
            get { return _repoSelectedItem; }
            set { _repoSelectedItem = value; }
        }

        string _repoAddedPageName = "";

        /// <summary>
        /// Gets or sets the value of variable repoAddedPageName.
        /// </summary>
        [TestVariable("ee505d0b-5904-48e8-8993-bab81144b2a5")]
        public string repoAddedPageName
        {
            get { return _repoAddedPageName; }
            set { _repoAddedPageName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c0b288b1-adc9-4642-a32e-5641551c150e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Dashboard folder.
        /// </summary>
        [RepositoryFolder("934797ae-8706-4401-9275-bf20491199a0")]
        public virtual Web_DashBoardRepositoryFolders.DashboardAppFolder Dashboard
        {
            get { return _dashboard; }
        }

        /// <summary>
        /// The Popup folder.
        /// </summary>
        [RepositoryFolder("f8dd0b14-8c4b-4718-91eb-90bc810a1649")]
        public virtual Web_DashBoardRepositoryFolders.PopupAppFolder Popup
        {
            get { return _popup; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Web_DashBoardRepositoryFolders
    {
        /// <summary>
        /// The DashboardAppFolder folder.
        /// </summary>
        [RepositoryFolder("934797ae-8706-4401-9275-bf20491199a0")]
        public partial class DashboardAppFolder : RepoGenBaseFolder
        {
            Web_DashBoardRepositoryFolders.LogInFolder _login;
            Web_DashBoardRepositoryFolders.MainFolder _main;
            Web_DashBoardRepositoryFolders.AddPageFolder _addpage;

            /// <summary>
            /// Creates a new Dashboard  folder.
            /// </summary>
            public DashboardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dashboard", "/dom[@domain='192.168.170.92']", parentFolder, 30000, null, false, "934797ae-8706-4401-9275-bf20491199a0", "")
            {
                _login = new Web_DashBoardRepositoryFolders.LogInFolder(this);
                _main = new Web_DashBoardRepositoryFolders.MainFolder(this);
                _addpage = new Web_DashBoardRepositoryFolders.AddPageFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("934797ae-8706-4401-9275-bf20491199a0")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("934797ae-8706-4401-9275-bf20491199a0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LogIn folder.
            /// </summary>
            [RepositoryFolder("ec188f65-3f25-4864-a8db-e4148ebf0625")]
            public virtual Web_DashBoardRepositoryFolders.LogInFolder LogIn
            {
                get { return _login; }
            }

            /// <summary>
            /// The Main folder.
            /// </summary>
            [RepositoryFolder("43cf54e7-0586-44a0-812a-b0d607df4153")]
            public virtual Web_DashBoardRepositoryFolders.MainFolder Main
            {
                get { return _main; }
            }

            /// <summary>
            /// The AddPage folder.
            /// </summary>
            [RepositoryFolder("040492da-98c7-4437-ad5c-e0b6c34aa3a2")]
            public virtual Web_DashBoardRepositoryFolders.AddPageFolder AddPage
            {
                get { return _addpage; }
            }
        }

        /// <summary>
        /// The LogInFolder folder.
        /// </summary>
        [RepositoryFolder("ec188f65-3f25-4864-a8db-e4148ebf0625")]
        public partial class LogInFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cbbrepositoryInfo;
            RepoItemInfo _txtusernameInfo;
            RepoItemInfo _txtpasswordInfo;
            RepoItemInfo _btnloginInfo;

            /// <summary>
            /// Creates a new LogIn  folder.
            /// </summary>
            public LogInFolder(RepoGenBaseFolder parentFolder) :
                    base("LogIn", "", parentFolder, 0, null, false, "ec188f65-3f25-4864-a8db-e4148ebf0625", "")
            {
                _cbbrepositoryInfo = new RepoItemInfo(this, "cbbRepository", ".//select[#'repository']", 30000, null, "fe09a122-4239-43e8-8e19-0347508f2b0a");
                _txtusernameInfo = new RepoItemInfo(this, "txtUsername", ".//input[#'username']", 30000, null, "1e5a7e31-ad3b-40c0-9c11-811b6d74177e");
                _txtpasswordInfo = new RepoItemInfo(this, "txtPassword", ".//input[#'password']", 30000, null, "2255e35a-19c6-4a77-a590-d1722ec75969");
                _btnloginInfo = new RepoItemInfo(this, "btnLogin", ".//div[@class='btn-login']", 30000, null, "92e47a16-ab8b-4f93-9071-777b5c61cee8");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ec188f65-3f25-4864-a8db-e4148ebf0625")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The cbbRepository item.
            /// </summary>
            [RepositoryItem("fe09a122-4239-43e8-8e19-0347508f2b0a")]
            public virtual Ranorex.SelectTag cbbRepository
            {
                get
                {
                    return _cbbrepositoryInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The cbbRepository item info.
            /// </summary>
            [RepositoryItemInfo("fe09a122-4239-43e8-8e19-0347508f2b0a")]
            public virtual RepoItemInfo cbbRepositoryInfo
            {
                get
                {
                    return _cbbrepositoryInfo;
                }
            }

            /// <summary>
            /// The txtUsername item.
            /// </summary>
            [RepositoryItem("1e5a7e31-ad3b-40c0-9c11-811b6d74177e")]
            public virtual Ranorex.InputTag txtUsername
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtUsername item info.
            /// </summary>
            [RepositoryItemInfo("1e5a7e31-ad3b-40c0-9c11-811b6d74177e")]
            public virtual RepoItemInfo txtUsernameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }

            /// <summary>
            /// The txtPassword item.
            /// </summary>
            [RepositoryItem("2255e35a-19c6-4a77-a590-d1722ec75969")]
            public virtual Ranorex.InputTag txtPassword
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtPassword item info.
            /// </summary>
            [RepositoryItemInfo("2255e35a-19c6-4a77-a590-d1722ec75969")]
            public virtual RepoItemInfo txtPasswordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }

            /// <summary>
            /// The btnLogin item.
            /// </summary>
            [RepositoryItem("92e47a16-ab8b-4f93-9071-777b5c61cee8")]
            public virtual Ranorex.DivTag btnLogin
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The btnLogin item info.
            /// </summary>
            [RepositoryItemInfo("92e47a16-ab8b-4f93-9071-777b5c61cee8")]
            public virtual RepoItemInfo btnLoginInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }
        }

        /// <summary>
        /// The MainFolder folder.
        /// </summary>
        [RepositoryFolder("43cf54e7-0586-44a0-812a-b0d607df4153")]
        public partial class MainFolder : RepoGenBaseFolder
        {
            Web_DashBoardRepositoryFolders.Header_MenuFolder _header_menu;
            Web_DashBoardRepositoryFolders.Main_MenuFolder _main_menu;

            /// <summary>
            /// Creates a new Main  folder.
            /// </summary>
            public MainFolder(RepoGenBaseFolder parentFolder) :
                    base("Main", "", parentFolder, 0, null, false, "43cf54e7-0586-44a0-812a-b0d607df4153", "")
            {
                _header_menu = new Web_DashBoardRepositoryFolders.Header_MenuFolder(this);
                _main_menu = new Web_DashBoardRepositoryFolders.Main_MenuFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("43cf54e7-0586-44a0-812a-b0d607df4153")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Header_Menu folder.
            /// </summary>
            [RepositoryFolder("3bca4313-6c40-45e7-9747-8b34ecd35e04")]
            public virtual Web_DashBoardRepositoryFolders.Header_MenuFolder Header_Menu
            {
                get { return _header_menu; }
            }

            /// <summary>
            /// The Main_Menu folder.
            /// </summary>
            [RepositoryFolder("f1f2dfbe-c345-43eb-90c3-a1d4f007a72d")]
            public virtual Web_DashBoardRepositoryFolders.Main_MenuFolder Main_Menu
            {
                get { return _main_menu; }
            }
        }

        /// <summary>
        /// The Header_MenuFolder folder.
        /// </summary>
        [RepositoryFolder("3bca4313-6c40-45e7-9747-8b34ecd35e04")]
        public partial class Header_MenuFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mnisignedinuserInfo;
            RepoItemInfo _mnilogoutInfo;

            /// <summary>
            /// Creates a new Header_Menu  folder.
            /// </summary>
            public Header_MenuFolder(RepoGenBaseFolder parentFolder) :
                    base("Header_Menu", "", parentFolder, 0, null, false, "3bca4313-6c40-45e7-9747-8b34ecd35e04", "")
            {
                _mnisignedinuserInfo = new RepoItemInfo(this, "mniSignedInUser", ".//div[#'header']//a[@href~'#Welcome']", 30000, null, "4a66ccf2-9821-4971-b5f3-c3264636c333");
                _mnilogoutInfo = new RepoItemInfo(this, "mniLogout", ".//div[#'header']//a[@href~'logout.do']", 30000, null, "4e1a0c03-e001-4fc0-ab94-ec096d3ddb7e");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3bca4313-6c40-45e7-9747-8b34ecd35e04")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The mniSignedInUser item.
            /// </summary>
            [RepositoryItem("4a66ccf2-9821-4971-b5f3-c3264636c333")]
            public virtual Ranorex.ATag mniSignedInUser
            {
                get
                {
                    return _mnisignedinuserInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The mniSignedInUser item info.
            /// </summary>
            [RepositoryItemInfo("4a66ccf2-9821-4971-b5f3-c3264636c333")]
            public virtual RepoItemInfo mniSignedInUserInfo
            {
                get
                {
                    return _mnisignedinuserInfo;
                }
            }

            /// <summary>
            /// The mniLogout item.
            /// </summary>
            [RepositoryItem("4e1a0c03-e001-4fc0-ab94-ec096d3ddb7e")]
            public virtual Ranorex.ATag mniLogout
            {
                get
                {
                    return _mnilogoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The mniLogout item info.
            /// </summary>
            [RepositoryItemInfo("4e1a0c03-e001-4fc0-ab94-ec096d3ddb7e")]
            public virtual RepoItemInfo mniLogoutInfo
            {
                get
                {
                    return _mnilogoutInfo;
                }
            }
        }

        /// <summary>
        /// The Main_MenuFolder folder.
        /// </summary>
        [RepositoryFolder("f1f2dfbe-c345-43eb-90c3-a1d4f007a72d")]
        public partial class Main_MenuFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mnisettingInfo;
            RepoItemInfo _mniglobalsetingselecteditemInfo;

            /// <summary>
            /// Creates a new Main_Menu  folder.
            /// </summary>
            public Main_MenuFolder(RepoGenBaseFolder parentFolder) :
                    base("Main_Menu", "", parentFolder, 0, null, false, "f1f2dfbe-c345-43eb-90c3-a1d4f007a72d", "")
            {
                _mnisettingInfo = new RepoItemInfo(this, "mniSetting", ".//div[#'main-menu']//li[@class='mn-setting']", 30000, null, "fc525480-bb7e-4ec4-bdda-eb9cab5d1fae");
                _mniglobalsetingselecteditemInfo = new RepoItemInfo(this, "mniGlobalSetingSelectedItem", ".//div[#'main-menu']//a[@innertext=$repoSelectedItem]", 30000, null, "d773694f-0bef-4f9f-8037-b2d0551b4fa8");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f1f2dfbe-c345-43eb-90c3-a1d4f007a72d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The mniSetting item.
            /// </summary>
            [RepositoryItem("fc525480-bb7e-4ec4-bdda-eb9cab5d1fae")]
            public virtual Ranorex.LiTag mniSetting
            {
                get
                {
                    return _mnisettingInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The mniSetting item info.
            /// </summary>
            [RepositoryItemInfo("fc525480-bb7e-4ec4-bdda-eb9cab5d1fae")]
            public virtual RepoItemInfo mniSettingInfo
            {
                get
                {
                    return _mnisettingInfo;
                }
            }

            /// <summary>
            /// The mniGlobalSetingSelectedItem item.
            /// </summary>
            [RepositoryItem("d773694f-0bef-4f9f-8037-b2d0551b4fa8")]
            public virtual Ranorex.ATag mniGlobalSetingSelectedItem
            {
                get
                {
                    return _mniglobalsetingselecteditemInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The mniGlobalSetingSelectedItem item info.
            /// </summary>
            [RepositoryItemInfo("d773694f-0bef-4f9f-8037-b2d0551b4fa8")]
            public virtual RepoItemInfo mniGlobalSetingSelectedItemInfo
            {
                get
                {
                    return _mniglobalsetingselecteditemInfo;
                }
            }
        }

        /// <summary>
        /// The AddPageFolder folder.
        /// </summary>
        [RepositoryFolder("040492da-98c7-4437-ad5c-e0b6c34aa3a2")]
        public partial class AddPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtnameInfo;
            RepoItemInfo _btnokInfo;
            RepoItemInfo _cbbparentInfo;
            RepoItemInfo _cbbnumberofcolumnInfo;
            RepoItemInfo _cbbdisplayafterInfo;
            RepoItemInfo _cbxpublicInfo;

            /// <summary>
            /// Creates a new AddPage  folder.
            /// </summary>
            public AddPageFolder(RepoGenBaseFolder parentFolder) :
                    base("AddPage", "", parentFolder, 0, null, false, "040492da-98c7-4437-ad5c-e0b6c34aa3a2", "")
            {
                _txtnameInfo = new RepoItemInfo(this, "txtName", ".//input[#'name']", 30000, null, "3d5ee29e-5aa9-430c-9aa1-9e4bcce27547");
                _btnokInfo = new RepoItemInfo(this, "btnOK", ".//input[#'OK']", 30000, null, "a0e40d1e-6d87-4a5f-aac4-c2d1e191db80");
                _cbbparentInfo = new RepoItemInfo(this, "cbbParent", ".//select[#'parent']", 30000, null, "f1584037-c898-48b9-a2c2-2a5df847dd1c");
                _cbbnumberofcolumnInfo = new RepoItemInfo(this, "cbbNumberOfColumn", ".//select[#'columnnumber']", 30000, null, "fde58011-d0b3-4de2-ac47-1fc87a0d3ae4");
                _cbbdisplayafterInfo = new RepoItemInfo(this, "cbbDisplayAfter", ".//select[#'afterpage']", 30000, null, "f7e9d182-8367-4171-815b-82f8f19c729b");
                _cbxpublicInfo = new RepoItemInfo(this, "cbxPublic", ".//input[#'ispublic']", 30000, null, "1d2acde9-e9a8-408c-8ea6-33bf7ec3133f");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("040492da-98c7-4437-ad5c-e0b6c34aa3a2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtName item.
            /// </summary>
            [RepositoryItem("3d5ee29e-5aa9-430c-9aa1-9e4bcce27547")]
            public virtual Ranorex.InputTag txtName
            {
                get
                {
                    return _txtnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtName item info.
            /// </summary>
            [RepositoryItemInfo("3d5ee29e-5aa9-430c-9aa1-9e4bcce27547")]
            public virtual RepoItemInfo txtNameInfo
            {
                get
                {
                    return _txtnameInfo;
                }
            }

            /// <summary>
            /// The btnOK item.
            /// </summary>
            [RepositoryItem("a0e40d1e-6d87-4a5f-aac4-c2d1e191db80")]
            public virtual Ranorex.InputTag btnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The btnOK item info.
            /// </summary>
            [RepositoryItemInfo("a0e40d1e-6d87-4a5f-aac4-c2d1e191db80")]
            public virtual RepoItemInfo btnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }

            /// <summary>
            /// The cbbParent item.
            /// </summary>
            [RepositoryItem("f1584037-c898-48b9-a2c2-2a5df847dd1c")]
            public virtual Ranorex.SelectTag cbbParent
            {
                get
                {
                    return _cbbparentInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The cbbParent item info.
            /// </summary>
            [RepositoryItemInfo("f1584037-c898-48b9-a2c2-2a5df847dd1c")]
            public virtual RepoItemInfo cbbParentInfo
            {
                get
                {
                    return _cbbparentInfo;
                }
            }

            /// <summary>
            /// The cbbNumberOfColumn item.
            /// </summary>
            [RepositoryItem("fde58011-d0b3-4de2-ac47-1fc87a0d3ae4")]
            public virtual Ranorex.SelectTag cbbNumberOfColumn
            {
                get
                {
                    return _cbbnumberofcolumnInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The cbbNumberOfColumn item info.
            /// </summary>
            [RepositoryItemInfo("fde58011-d0b3-4de2-ac47-1fc87a0d3ae4")]
            public virtual RepoItemInfo cbbNumberOfColumnInfo
            {
                get
                {
                    return _cbbnumberofcolumnInfo;
                }
            }

            /// <summary>
            /// The cbbDisplayAfter item.
            /// </summary>
            [RepositoryItem("f7e9d182-8367-4171-815b-82f8f19c729b")]
            public virtual Ranorex.SelectTag cbbDisplayAfter
            {
                get
                {
                    return _cbbdisplayafterInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The cbbDisplayAfter item info.
            /// </summary>
            [RepositoryItemInfo("f7e9d182-8367-4171-815b-82f8f19c729b")]
            public virtual RepoItemInfo cbbDisplayAfterInfo
            {
                get
                {
                    return _cbbdisplayafterInfo;
                }
            }

            /// <summary>
            /// The cbxPublic item.
            /// </summary>
            [RepositoryItem("1d2acde9-e9a8-408c-8ea6-33bf7ec3133f")]
            public virtual Ranorex.InputTag cbxPublic
            {
                get
                {
                    return _cbxpublicInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The cbxPublic item info.
            /// </summary>
            [RepositoryItemInfo("1d2acde9-e9a8-408c-8ea6-33bf7ec3133f")]
            public virtual RepoItemInfo cbxPublicInfo
            {
                get
                {
                    return _cbxpublicInfo;
                }
            }
        }

        /// <summary>
        /// The PopupAppFolder folder.
        /// </summary>
        [RepositoryFolder("f8dd0b14-8c4b-4718-91eb-90bc810a1649")]
        public partial class PopupAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new Popup  folder.
            /// </summary>
            public PopupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Popup", "/form[@title>'TestArchitect' or @title='Message from webpage']", parentFolder, 30000, null, true, "f8dd0b14-8c4b-4718-91eb-90bc810a1649", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", ".//button[@accessiblename='OK' or @text='OK']", 30000, null, "a7e5b9cb-4d83-4999-af64-c74a7e067f9f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f8dd0b14-8c4b-4718-91eb-90bc810a1649")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f8dd0b14-8c4b-4718-91eb-90bc810a1649")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("a7e5b9cb-4d83-4999-af64-c74a7e067f9f")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("a7e5b9cb-4d83-4999-af64-c74a7e067f9f")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
