///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using OpenQA.Selenium;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;
using TADashboard_Modules.Extension;
using TADashboard_Modules.Helper_modules;

namespace TADashboard_Modules.Browser_modules.Dialog
{
    public partial class SelectOk
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Click_ButtonOK(RepoItemInfo buttonInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttonInfo' at Center.", buttonInfo);
            if (WebDriverExtension.IsWebDriverEndPoint())
			{
            	WebDriverExtension.WaitForAlert(5000);
        		var webDriver = WebDriverExtension.GetCurrentWebDriver();
        		webDriver.SwitchTo().Alert().Accept();
			}
			else
			{
				buttonInfo.FindAdapter<Button>().Click();
			}
        }

    }
}
