///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TADashboard_Modules.Page_modules.Base.MainMenu
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SelectSetting recording.
    /// </summary>
    [TestModule("5eafb320-c6bf-4bdc-9214-eb32eaf2b2be", ModuleType.Recording, 1)]
    public partial class SelectSetting : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::TADashboard_Modules.TADashboard_Repository repository.
        /// </summary>
        public static global::TADashboard_Modules.TADashboard_Repository repo = global::TADashboard_Modules.TADashboard_Repository.Instance;

        static SelectSetting instance = new SelectSetting();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SelectSetting()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SelectSetting Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable repoBrowserName.
        /// </summary>
        [TestVariable("0bbdec9e-d077-4ab9-b70e-458c78ba6e1d")]
        public string repoBrowserName
        {
            get { return repo.repoBrowserName; }
            set { repo.repoBrowserName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable repoSettingName.
        /// </summary>
        [TestVariable("a04b4e4c-053a-4df7-ad51-7204c6d71e69")]
        public string repoSettingName
        {
            get { return repo.repoSettingName; }
            set { repo.repoSettingName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Hover on Setting icon
            Report.Log(ReportLevel.Info, "Mouse", "Hover on Setting icon\r\nMouse Left Move item 'TADashboard.Pages.BasePage.MainMenu.LnkSetting' at Center.", repo.TADashboard.Pages.BasePage.MainMenu.LnkSettingInfo, new RecordItemIndex(0));
            repo.TADashboard.Pages.BasePage.MainMenu.LnkSetting.MoveTo();
            Delay.Milliseconds(0);
            
            // Select setting
            Report.Log(ReportLevel.Info, "Mouse", "Select setting\r\nMouse Left Click item 'TADashboard.Pages.BasePage.MainMenu.GlobalSetting.LnkSetting' at Center.", repo.TADashboard.Pages.BasePage.MainMenu.GlobalSetting.LnkSettingInfo, new RecordItemIndex(1));
            repo.TADashboard.Pages.BasePage.MainMenu.GlobalSetting.LnkSetting.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
