///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace mobileSol.Recording_Modules.PanelsPage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SelectPanel recording.
    /// </summary>
    [TestModule("ab86465d-8fbd-4471-80b4-4eb1fbcb9252", ModuleType.Recording, 1)]
    public partial class SelectPanel : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::mobileSol.mobileSolRepository repository.
        /// </summary>
        public static global::mobileSol.mobileSolRepository repo = global::mobileSol.mobileSolRepository.Instance;

        static SelectPanel instance = new SelectPanel();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SelectPanel()
        {
            modPanelName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SelectPanel Instance
        {
            get { return instance; }
        }

#region Variables

        string _modPanelName;

        /// <summary>
        /// Gets or sets the value of variable modPanelName.
        /// </summary>
        [TestVariable("4d26bb6e-e194-4aa0-8397-d780cfe773fc")]
        public string modPanelName
        {
            get { return _modPanelName; }
            set { _modPanelName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Common.Utility.SelectItemInTable(repo.Browser.PanelsPage.TblResult.SelfInfo, modPanelName, "Panel Name");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
