///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DesktopApp_Modules.ApplicationModules.Notepad
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeleteFile recording.
    /// </summary>
    [TestModule("2eb0b3b6-3579-4d8b-bd74-28ec3b46a358", ModuleType.Recording, 1)]
    public partial class DeleteFile : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DesktopApp_Modules.DesktopApp_ModulesRepository repository.
        /// </summary>
        public static global::DesktopApp_Modules.DesktopApp_ModulesRepository repo = global::DesktopApp_Modules.DesktopApp_ModulesRepository.Instance;

        static DeleteFile instance = new DeleteFile();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeleteFile()
        {
            varLocalPath = "";
            varFileSetupName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeleteFile Instance
        {
            get { return instance; }
        }

#region Variables

        string _varLocalPath;

        /// <summary>
        /// Gets or sets the value of variable varLocalPath.
        /// </summary>
        [TestVariable("ae0dc919-078b-4d9e-9f17-56c00a49a5e6")]
        public string varLocalPath
        {
            get { return _varLocalPath; }
            set { _varLocalPath = value; }
        }

        string _varFileSetupName;

        /// <summary>
        /// Gets or sets the value of variable varFileSetupName.
        /// </summary>
        [TestVariable("5a6c1bab-4299-4213-a09e-6f46f255c52b")]
        public string varFileSetupName
        {
            get { return _varFileSetupName; }
            set { _varFileSetupName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Ranorex.AutomationHelpers.UserCodeCollections.FileLibrary.DeleteFiles(varLocalPath, varFileSetupName);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
