///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DesktopApp_Modules.ApplicationModules.Notepad
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InstallApp recording.
    /// </summary>
    [TestModule("5c2fb7c1-bef7-495e-8078-58f859991342", ModuleType.Recording, 1)]
    public partial class InstallApp : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DesktopApp_Modules.DesktopApp_ModulesRepository repository.
        /// </summary>
        public static global::DesktopApp_Modules.DesktopApp_ModulesRepository repo = global::DesktopApp_Modules.DesktopApp_ModulesRepository.Instance;

        static InstallApp instance = new InstallApp();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InstallApp()
        {
            varStartApp = "D:\\pycharm-professional-2020.1.2.exe";
            repoProcessName = "pycharm-professional-2020.1.2";
            repoProcessNameScreenApp = "pycharm64";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InstallApp Instance
        {
            get { return instance; }
        }

#region Variables

        string _varStartApp;

        /// <summary>
        /// Gets or sets the value of variable varStartApp.
        /// </summary>
        [TestVariable("63b67a07-fb9f-4e4b-9fa4-7ec2b13592a1")]
        public string varStartApp
        {
            get { return _varStartApp; }
            set { _varStartApp = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable repoProcessName.
        /// </summary>
        [TestVariable("28ba20a8-c71d-48fb-93bf-651e889402cf")]
        public string repoProcessName
        {
            get { return repo.repoProcessName; }
            set { repo.repoProcessName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable repoProcessNameScreenApp.
        /// </summary>
        [TestVariable("f932be9f-bdab-4342-8312-f6361a48bc95")]
        public string repoProcessNameScreenApp
        {
            get { return repo.repoProcessNameScreenApp; }
            set { repo.repoProcessNameScreenApp = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application with file name from variable $varStartApp in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication(varStartApp, "", "", false);
            Delay.Milliseconds(0);
            
            Mouse_Click_ButtonOK(repo.Application.ButtonOKInfo);
            Delay.Milliseconds(0);
            
            Mouse_Click_ButtonNext(repo.Application.SetupApp.ButtonNextInfo);
            Delay.Milliseconds(0);
            
            Mouse_Click_IAgree(repo.Application.SetupApp.IAgreeInfo);
            Delay.Milliseconds(0);
            
            Mouse_Click_ButtonNext1(repo.Application.SetupApp.ButtonNextInfo);
            Delay.Milliseconds(0);
            
            Mouse_Click_ButtonInstall(repo.Application.SetupApp.ButtonInstallInfo);
            Delay.Milliseconds(0);
            
            Mouse_Click_ButtonFinish(repo.Application.SetupApp.ButtonFinishInfo);
            Delay.Milliseconds(0);
            
            Mouse_Click_Close(repo.Application.ScreenApp.CloseInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
