///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Web_DashBoard.Record_Actions
{
    public partial class CheckPageIsNavigated
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

         public string GeneratePageName(string name, string type)
        {        
        	string pageName = "";
        	if (type.ToLower() == "new" && name == "[Dynamic]" ) {
        		pageName = "Test_" + System.DateTime.Now.ToString("yyyyMMdd");
        	}
        	else if (type.ToLower() == "update" && name == "[Dynamic]") {
        		
        		pageName = "Test_" + System.DateTime.Now.ToString("yyyyMMdd") + "_Updated";
        	}
        	return pageName;
        }
        public void Validate_Dashboard(RepoItemInfo webdocumentInfo, string navigatedPageName)
        {        	
            Report.Log(ReportLevel.Info, "Validation", "Validating Page "+ navigatedPageName +" is navigated'.", webdocumentInfo);
           	Validate.AttributeEqual(webdocumentInfo, "Caption", "TestArchitect ™ - "+ navigatedPageName);
        }

    }
}
