///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DesktopApp_Automation.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UninstallApp recording.
    /// </summary>
    [TestModule("113054de-f97e-4533-90a3-1b968541ae5e", ModuleType.Recording, 1)]
    public partial class UninstallApp : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DesktopApp_Automation.DesktopApp_AutomationRepository repository.
        /// </summary>
        public static global::DesktopApp_Automation.DesktopApp_AutomationRepository repo = global::DesktopApp_Automation.DesktopApp_AutomationRepository.Instance;

        static UninstallApp instance = new UninstallApp();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UninstallApp()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UninstallApp Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.FileExplorer' at 17;23.", repo.Explorer.FileExplorerInfo, new RecordItemIndex(0));
            repo.Explorer.FileExplorer.Click("17;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'FileExplorer.ThisPC' at 18;6.", repo.FileExplorer.ThisPCInfo, new RecordItemIndex(1));
            repo.FileExplorer.ThisPC.Click(System.Windows.Forms.MouseButtons.Right, "18;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer1.Properties' at 92;10.", repo.Explorer1.PropertiesInfo, new RecordItemIndex(2));
            repo.Explorer1.Properties.Click("92;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'System.CPLink' at 75;5.", repo.System.CPLinkInfo, new RecordItemIndex(3));
            repo.System.CPLink.Click("75;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ControlPanel.Tasklink' at 47;8.", repo.ControlPanel.TasklinkInfo, new RecordItemIndex(4));
            repo.ControlPanel.Tasklink.Click("47;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Notepad++ (64-bit x64)') on item 'ProgramsAndFeatures.NotepadPlusPlus64BitX64'.", repo.ProgramsAndFeatures.NotepadPlusPlus64BitX64Info, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ProgramsAndFeatures.NotepadPlusPlus64BitX64Info, "Text", "Notepad++ (64-bit x64)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'ProgramsAndFeatures.NotepadPlusPlus64BitX64' at 120;10.", repo.ProgramsAndFeatures.NotepadPlusPlus64BitX64Info, new RecordItemIndex(6));
            repo.ProgramsAndFeatures.NotepadPlusPlus64BitX64.Click(System.Windows.Forms.MouseButtons.Right, "120;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer1.Uninstall' at 47;11.", repo.Explorer1.UninstallInfo, new RecordItemIndex(7));
            repo.Explorer1.Uninstall.Click("47;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NotepadPlusPlusV786Uninstall.ButtonUninstall' at 15;13.", repo.NotepadPlusPlusV786Uninstall.ButtonUninstallInfo, new RecordItemIndex(8));
            repo.NotepadPlusPlusV786Uninstall.ButtonUninstall.Click("15;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NotepadPlusPlusV786Uninstall1.ButtonNo' at 33;13.", repo.NotepadPlusPlusV786Uninstall1.ButtonNoInfo, new RecordItemIndex(9));
            repo.NotepadPlusPlusV786Uninstall1.ButtonNo.Click("33;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NotepadPlusPlusV786Uninstall.ButtonClose' at 27;10.", repo.NotepadPlusPlusV786Uninstall.ButtonCloseInfo, new RecordItemIndex(10));
            repo.NotepadPlusPlusV786Uninstall.ButtonClose.Click("27;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProgramsAndFeatures.Close' at 17;5.", repo.ProgramsAndFeatures.CloseInfo, new RecordItemIndex(11));
            repo.ProgramsAndFeatures.Close.Click("17;5");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
