///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TADashboard_Modules.Business_modules.Popups.PagePopup
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EnterPageInfo recording.
    /// </summary>
    [TestModule("45db5947-fa9f-4a3f-8d8a-61d63b03451b", ModuleType.Recording, 1)]
    public partial class EnterPageInfo : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::TADashboard_Modules.TADashboard_Repository repository.
        /// </summary>
        public static global::TADashboard_Modules.TADashboard_Repository repo = global::TADashboard_Modules.TADashboard_Repository.Instance;

        static EnterPageInfo instance = new EnterPageInfo();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EnterPageInfo()
        {
            modPageName = "";
            modColNumber = "";
            modParentPage = "";
            modDisplayAfter = "";
            modIsPublic = "False";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EnterPageInfo Instance
        {
            get { return instance; }
        }

#region Variables

        string _modPageName;

        /// <summary>
        /// Gets or sets the value of variable modPageName.
        /// </summary>
        [TestVariable("448990e5-fcdf-4ec7-8279-8c8cee101849")]
        public string modPageName
        {
            get { return _modPageName; }
            set { _modPageName = value; }
        }

        string _modColNumber;

        /// <summary>
        /// Gets or sets the value of variable modColNumber.
        /// </summary>
        [TestVariable("1487c30f-5662-4fad-8bf7-e8f5ab9a5919")]
        public string modColNumber
        {
            get { return _modColNumber; }
            set { _modColNumber = value; }
        }

        string _modParentPage;

        /// <summary>
        /// Gets or sets the value of variable modParentPage.
        /// </summary>
        [TestVariable("862889ec-f2b6-4f16-b92e-4c3e2e417e98")]
        public string modParentPage
        {
            get { return _modParentPage; }
            set { _modParentPage = value; }
        }

        string _modDisplayAfter;

        /// <summary>
        /// Gets or sets the value of variable modDisplayAfter.
        /// </summary>
        [TestVariable("08fce4f2-797d-4690-aa14-a9f644f236c8")]
        public string modDisplayAfter
        {
            get { return _modDisplayAfter; }
            set { _modDisplayAfter = value; }
        }

        string _modIsPublic;

        /// <summary>
        /// Gets or sets the value of variable modIsPublic.
        /// </summary>
        [TestVariable("a914e309-757a-4feb-ac46-b02a81745f8c")]
        public string modIsPublic
        {
            get { return _modIsPublic; }
            set { _modIsPublic = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Helper_modules.ControlExtension.InputText(repo.TADashboard.Popups.PagePopup.TxtPageNameInfo, modPageName);
            Delay.Milliseconds(0);
            
            Helper_modules.ControlExtension.SelectByText(repo.TADashboard.Popups.PagePopup.CbxParentPageInfo, modParentPage);
            Delay.Milliseconds(0);
            
            Helper_modules.ControlExtension.SelectByText(repo.TADashboard.Popups.PagePopup.CbxNumberOfColumnsInfo, modColNumber);
            Delay.Milliseconds(0);
            
            Helper_modules.ControlExtension.SelectByText(repo.TADashboard.Popups.PagePopup.CbxDisplayAfterInfo, modDisplayAfter);
            Delay.Milliseconds(0);
            
            Helper_modules.ControlExtension.SetCheckedState(repo.TADashboard.Popups.PagePopup.ChkIsPublicInfo, modIsPublic);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
