///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DesktopApp_Modules.ApplicationModules.ControlPanel
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateInstalled recording.
    /// </summary>
    [TestModule("6b238876-72f3-40a2-97ba-4ecf35e8c515", ModuleType.Recording, 1)]
    public partial class ValidateInstalled : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DesktopApp_Modules.DesktopApp_ModulesRepository repository.
        /// </summary>
        public static global::DesktopApp_Modules.DesktopApp_ModulesRepository repo = global::DesktopApp_Modules.DesktopApp_ModulesRepository.Instance;

        static ValidateInstalled instance = new ValidateInstalled();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateInstalled()
        {
            varSoftwareName = "Notepad++ (64-bit x64)";
            repoVersionApp = "7.8.6";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateInstalled Instance
        {
            get { return instance; }
        }

#region Variables

        string _varSoftwareName;

        /// <summary>
        /// Gets or sets the value of variable varSoftwareName.
        /// </summary>
        [TestVariable("5902be29-de50-4d29-b3ce-4662954e7f01")]
        public string varSoftwareName
        {
            get { return _varSoftwareName; }
            set { _varSoftwareName = value; }
        }

        string _repoVersionApp;

        /// <summary>
        /// Gets or sets the value of variable repoVersionApp.
        /// </summary>
        [TestVariable("c33a7b58-c069-4176-98d7-9637f83d8b63")]
        public string repoVersionApp
        {
            get { return _repoVersionApp; }
            set { _repoVersionApp = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable repoSoftwareName.
        /// </summary>
        [TestVariable("17312650-b8ff-4723-8ac4-27f8eed9d1c2")]
        public string repoSoftwareName
        {
            get { return repo.repoSoftwareName; }
            set { repo.repoSoftwareName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$varSoftwareName) on item 'ProgramsAndFeatures.ApplicationListItem'.", repo.ProgramsAndFeatures.ApplicationListItemInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ProgramsAndFeatures.ApplicationListItemInfo, "Text", varSoftwareName);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
