///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TADashboard_Modules.Page_modules.Login
{
    public partial class LoginToDashboard
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Set_value_CbxRepository(RepoItemInfo selecttagInfo)
        {
        	if (!string.IsNullOrEmpty(varDashboardRepo))
        	{
        		Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$dashboardRepo' on item 'selecttagInfo'.", selecttagInfo);
            	selecttagInfo.FindAdapter<SelectTag>().Element.SetAttributeValue("TagValue", varDashboardRepo);
        	}
        }

        public void Key_sequence_TxtUsername(RepoItemInfo inputtagInfo)
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varUsername' with focus on 'inputtagInfo'.", inputtagInfo);
            inputtagInfo.FindAdapter<InputTag>().PressKeys(varUsername);
        }

    }
}
