///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DesktopApp_Modules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DesktopApp_ModulesRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("43f9a22b-83ee-4a35-a13f-fe3b69b8da65")]
    public partial class DesktopApp_ModulesRepository : RepoGenBaseFolder
    {
        static DesktopApp_ModulesRepository instance = new DesktopApp_ModulesRepository();

        /// <summary>
        /// Gets the singleton class instance representing the DesktopApp_ModulesRepository element repository.
        /// </summary>
        [RepositoryFolder("43f9a22b-83ee-4a35-a13f-fe3b69b8da65")]
        public static DesktopApp_ModulesRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DesktopApp_ModulesRepository() 
            : base("DesktopApp_ModulesRepository", "/", null, 0, false, "43f9a22b-83ee-4a35-a13f-fe3b69b8da65", ".\\RepositoryImages\\DesktopApp_ModulesRepository43f9a22b.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("43f9a22b-83ee-4a35-a13f-fe3b69b8da65")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DesktopApp_ModulesRepositoryFolders
    {
    }
#pragma warning restore 0436
}
