///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DesktopApp_Modules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DesktopApp_ModulesRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("43f9a22b-83ee-4a35-a13f-fe3b69b8da65")]
    public partial class DesktopApp_ModulesRepository : RepoGenBaseFolder
    {
        static DesktopApp_ModulesRepository instance = new DesktopApp_ModulesRepository();
        DesktopApp_ModulesRepositoryFolders.ProgramsAndFeaturesAppFolder _programsandfeatures;
        DesktopApp_ModulesRepositoryFolders.ApplicationFolder _application;
        DesktopApp_ModulesRepositoryFolders.UninstallAppAppFolder _uninstallapp;
        DesktopApp_ModulesRepositoryFolders.ExplorerAppFolder _explorer;
        DesktopApp_ModulesRepositoryFolders.ControlPanelAppFolder _controlpanel;

        /// <summary>
        /// Gets the singleton class instance representing the DesktopApp_ModulesRepository element repository.
        /// </summary>
        [RepositoryFolder("43f9a22b-83ee-4a35-a13f-fe3b69b8da65")]
        public static DesktopApp_ModulesRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DesktopApp_ModulesRepository() 
            : base("DesktopApp_ModulesRepository", "/", null, 0, false, "43f9a22b-83ee-4a35-a13f-fe3b69b8da65", ".\\RepositoryImages\\DesktopApp_ModulesRepository43f9a22b.rximgres")
        {
            _programsandfeatures = new DesktopApp_ModulesRepositoryFolders.ProgramsAndFeaturesAppFolder(this);
            _application = new DesktopApp_ModulesRepositoryFolders.ApplicationFolder(this);
            _uninstallapp = new DesktopApp_ModulesRepositoryFolders.UninstallAppAppFolder(this);
            _explorer = new DesktopApp_ModulesRepositoryFolders.ExplorerAppFolder(this);
            _controlpanel = new DesktopApp_ModulesRepositoryFolders.ControlPanelAppFolder(this);
        }

#region Variables

        string _repoSoftwareName = "PyCharm 2020.1.2";

        /// <summary>
        /// Gets or sets the value of variable repoSoftwareName.
        /// </summary>
        [TestVariable("17312650-b8ff-4723-8ac4-27f8eed9d1c2")]
        public string repoSoftwareName
        {
            get { return _repoSoftwareName; }
            set { _repoSoftwareName = value; }
        }

        string _repoUninstallApp = "PyCharm Uninstall";

        /// <summary>
        /// Gets or sets the value of variable repoUninstallApp.
        /// </summary>
        [TestVariable("7eef9d79-fb2e-4df1-8e6b-44bbe41bc9f9")]
        public string repoUninstallApp
        {
            get { return _repoUninstallApp; }
            set { _repoUninstallApp = value; }
        }

        string _repoProcessName = "pycharm-professional-2020.1.2";

        /// <summary>
        /// Gets or sets the value of variable repoProcessName.
        /// </summary>
        [TestVariable("28ba20a8-c71d-48fb-93bf-651e889402cf")]
        public string repoProcessName
        {
            get { return _repoProcessName; }
            set { _repoProcessName = value; }
        }

        string _repoProcessNameScreenApp = "pycharm64";

        /// <summary>
        /// Gets or sets the value of variable repoProcessNameScreenApp.
        /// </summary>
        [TestVariable("f932be9f-bdab-4342-8312-f6361a48bc95")]
        public string repoProcessNameScreenApp
        {
            get { return _repoProcessNameScreenApp; }
            set { _repoProcessNameScreenApp = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("43f9a22b-83ee-4a35-a13f-fe3b69b8da65")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ProgramsAndFeatures folder.
        /// </summary>
        [RepositoryFolder("b56fa4ab-1b07-4def-be6a-431c28f935b4")]
        public virtual DesktopApp_ModulesRepositoryFolders.ProgramsAndFeaturesAppFolder ProgramsAndFeatures
        {
            get { return _programsandfeatures; }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("35a2a86a-d9ea-4d32-bc93-1b8973073364")]
        public virtual DesktopApp_ModulesRepositoryFolders.ApplicationFolder Application
        {
            get { return _application; }
        }

        /// <summary>
        /// The UninstallApp folder.
        /// </summary>
        [RepositoryFolder("b68af8ab-5363-46b4-b475-56302d974dd2")]
        public virtual DesktopApp_ModulesRepositoryFolders.UninstallAppAppFolder UninstallApp
        {
            get { return _uninstallapp; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("7d3fb789-93fd-4f24-b21b-1d4a9e55c998")]
        public virtual DesktopApp_ModulesRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The ControlPanel folder.
        /// </summary>
        [RepositoryFolder("85df6248-2b37-4e80-bf55-340192a87131")]
        public virtual DesktopApp_ModulesRepositoryFolders.ControlPanelAppFolder ControlPanel
        {
            get { return _controlpanel; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DesktopApp_ModulesRepositoryFolders
    {
        /// <summary>
        /// The ProgramsAndFeaturesAppFolder folder.
        /// </summary>
        [RepositoryFolder("b56fa4ab-1b07-4def-be6a-431c28f935b4")]
        public partial class ProgramsAndFeaturesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closebuttonInfo;
            RepoItemInfo _tasklinkInfo;
            RepoItemInfo _uninstallInfo;
            RepoItemInfo _applicationlistitemInfo;

            /// <summary>
            /// Creates a new ProgramsAndFeatures  folder.
            /// </summary>
            public ProgramsAndFeaturesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ProgramsAndFeatures", "/form[@title='Programs and Features']", parentFolder, 30000, null, true, "b56fa4ab-1b07-4def-be6a-431c28f935b4", "")
            {
                _closebuttonInfo = new RepoItemInfo(this, "CloseButton", "titlebar/button[@accessiblename='Close']", 30000, null, "6bd297b2-f310-4944-8604-0b031db7639e");
                _tasklinkInfo = new RepoItemInfo(this, "Tasklink", ".//container[@automationid='FolderLayoutContainer']/container[@automationid='CategoryPanel']/link[@name='Uninstall a program']", 30000, null, "1edbcd07-1a12-49a1-9c1b-c7692aa86fe1");
                _uninstallInfo = new RepoItemInfo(this, "Uninstall", ".//container[@caption='Explorer Pane']/container[@accessiblename='Folder Layout Pane']/?/?/toolbar[@accessiblename='Command Module']/button[@accessiblename='Uninstall']", 30000, null, "ab9f5283-2c62-4394-bf4d-f21ace327c91");
                _applicationlistitemInfo = new RepoItemInfo(this, "ApplicationListItem", ".//container[@caption='Explorer Pane']/container[@accessiblename='Folder Layout Pane']/?/?/container[@accessiblename='Shell Folder View']/list[@accessiblename='Folder View']/listitem[@accessiblename=$repoSoftwareName]", 30000, null, "ac5dadcf-7bf6-48ef-b9c5-33cfa0cdc015");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b56fa4ab-1b07-4def-be6a-431c28f935b4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b56fa4ab-1b07-4def-be6a-431c28f935b4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CloseButton item.
            /// </summary>
            [RepositoryItem("6bd297b2-f310-4944-8604-0b031db7639e")]
            public virtual Ranorex.Button CloseButton
            {
                get
                {
                    return _closebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseButton item info.
            /// </summary>
            [RepositoryItemInfo("6bd297b2-f310-4944-8604-0b031db7639e")]
            public virtual RepoItemInfo CloseButtonInfo
            {
                get
                {
                    return _closebuttonInfo;
                }
            }

            /// <summary>
            /// The Tasklink item.
            /// </summary>
            [RepositoryItem("1edbcd07-1a12-49a1-9c1b-c7692aa86fe1")]
            public virtual Ranorex.Link Tasklink
            {
                get
                {
                    return _tasklinkInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The Tasklink item info.
            /// </summary>
            [RepositoryItemInfo("1edbcd07-1a12-49a1-9c1b-c7692aa86fe1")]
            public virtual RepoItemInfo TasklinkInfo
            {
                get
                {
                    return _tasklinkInfo;
                }
            }

            /// <summary>
            /// The Uninstall item.
            /// </summary>
            [RepositoryItem("ab9f5283-2c62-4394-bf4d-f21ace327c91")]
            public virtual Ranorex.Button Uninstall
            {
                get
                {
                    return _uninstallInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Uninstall item info.
            /// </summary>
            [RepositoryItemInfo("ab9f5283-2c62-4394-bf4d-f21ace327c91")]
            public virtual RepoItemInfo UninstallInfo
            {
                get
                {
                    return _uninstallInfo;
                }
            }

            /// <summary>
            /// The ApplicationListItem item.
            /// </summary>
            [RepositoryItem("ac5dadcf-7bf6-48ef-b9c5-33cfa0cdc015")]
            public virtual Ranorex.ListItem ApplicationListItem
            {
                get
                {
                    return _applicationlistitemInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ApplicationListItem item info.
            /// </summary>
            [RepositoryItemInfo("ac5dadcf-7bf6-48ef-b9c5-33cfa0cdc015")]
            public virtual RepoItemInfo ApplicationListItemInfo
            {
                get
                {
                    return _applicationlistitemInfo;
                }
            }
        }

        /// <summary>
        /// The ApplicationFolder folder.
        /// </summary>
        [RepositoryFolder("35a2a86a-d9ea-4d32-bc93-1b8973073364")]
        public partial class ApplicationFolder : RepoGenBaseFolder
        {
            DesktopApp_ModulesRepositoryFolders.ScreenAppFolder _screenapp;
            DesktopApp_ModulesRepositoryFolders.SetupAppAppFolder _setupapp;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "", parentFolder, 0, null, false, "35a2a86a-d9ea-4d32-bc93-1b8973073364", "")
            {
                _screenapp = new DesktopApp_ModulesRepositoryFolders.ScreenAppFolder(this);
                _setupapp = new DesktopApp_ModulesRepositoryFolders.SetupAppAppFolder(this);
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "/form[@title='Installer Language']/button[@text='OK']", 30000, null, "a8754ebe-35b0-4e5f-a8a7-e92f47cd60d4");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("35a2a86a-d9ea-4d32-bc93-1b8973073364")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("a8754ebe-35b0-4e5f-a8a7-e92f47cd60d4")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("a8754ebe-35b0-4e5f-a8a7-e92f47cd60d4")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The ScreenApp folder.
            /// </summary>
            [RepositoryFolder("8fe543ea-4f32-4c74-96d1-82c001623676")]
            public virtual DesktopApp_ModulesRepositoryFolders.ScreenAppFolder ScreenApp
            {
                get { return _screenapp; }
            }

            /// <summary>
            /// The SetupApp folder.
            /// </summary>
            [RepositoryFolder("6575f404-b48e-44c9-8d49-e7be5141ccc9")]
            public virtual DesktopApp_ModulesRepositoryFolders.SetupAppAppFolder SetupApp
            {
                get { return _setupapp; }
            }
        }

        /// <summary>
        /// The ScreenAppFolder folder.
        /// </summary>
        [RepositoryFolder("8fe543ea-4f32-4c74-96d1-82c001623676")]
        public partial class ScreenAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new ScreenApp  folder.
            /// </summary>
            public ScreenAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ScreenApp", "/form[@processname=$repoProcessNameScreenApp]", parentFolder, 30000, null, false, "8fe543ea-4f32-4c74-96d1-82c001623676", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "055630ef-5419-4f39-8729-7e882bc372fc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8fe543ea-4f32-4c74-96d1-82c001623676")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8fe543ea-4f32-4c74-96d1-82c001623676")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("055630ef-5419-4f39-8729-7e882bc372fc")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("055630ef-5419-4f39-8729-7e882bc372fc")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The SetupAppAppFolder folder.
        /// </summary>
        [RepositoryFolder("6575f404-b48e-44c9-8d49-e7be5141ccc9")]
        public partial class SetupAppAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _iagreeInfo;
            RepoItemInfo _buttonnextInfo;
            RepoItemInfo _buttonfinishInfo;
            RepoItemInfo _cancelInfo;
            RepoItemInfo _buttonbackInfo;
            RepoItemInfo _browseInfo;
            RepoItemInfo _destinationfolderInfo;
            RepoItemInfo _buttoninstallInfo;

            /// <summary>
            /// Creates a new SetupApp  folder.
            /// </summary>
            public SetupAppAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SetupApp", "/form[@processname=$repoProcessName]", parentFolder, 30000, null, false, "6575f404-b48e-44c9-8d49-e7be5141ccc9", "")
            {
                _iagreeInfo = new RepoItemInfo(this, "IAgree", "button[@text='I &Agree']", 30000, null, "5dee88ae-8723-48fb-8469-72c95a92ad7b");
                _buttonnextInfo = new RepoItemInfo(this, "ButtonNext", "button[@text='&Next >']", 30000, null, "f75a8ed8-e22c-4d8f-8537-fd11578122bf");
                _buttonfinishInfo = new RepoItemInfo(this, "ButtonFinish", "button[@text='&Finish']", 30000, null, "17f37782-4773-400d-9dd6-ea1620177f84");
                _cancelInfo = new RepoItemInfo(this, "Cancel", "button[@text='Cancel']", 30000, null, "a2d3d280-7214-40f3-82a9-55a651fc0849");
                _buttonbackInfo = new RepoItemInfo(this, "ButtonBack", "button[@text='< &Back']", 30000, null, "4f600f5a-5ca6-4fba-8ed2-2e552135365d");
                _browseInfo = new RepoItemInfo(this, "Browse", "?/?/button[@text='B&rowse...']", 30000, null, "2738961d-d45d-43e5-87fb-664e5606cd88");
                _destinationfolderInfo = new RepoItemInfo(this, "DestinationFolder", "?/?/container[@controlid='1020']/container[@accessiblename='Destination Folder']", 30000, null, "0d1551f6-587a-496f-b412-14766683641b");
                _buttoninstallInfo = new RepoItemInfo(this, "ButtonInstall", "button[@text='&Install']", 30000, null, "fd62e641-1c11-427e-b47f-a4dfdd4ea88a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6575f404-b48e-44c9-8d49-e7be5141ccc9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6575f404-b48e-44c9-8d49-e7be5141ccc9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IAgree item.
            /// </summary>
            [RepositoryItem("5dee88ae-8723-48fb-8469-72c95a92ad7b")]
            public virtual Ranorex.Button IAgree
            {
                get
                {
                    return _iagreeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The IAgree item info.
            /// </summary>
            [RepositoryItemInfo("5dee88ae-8723-48fb-8469-72c95a92ad7b")]
            public virtual RepoItemInfo IAgreeInfo
            {
                get
                {
                    return _iagreeInfo;
                }
            }

            /// <summary>
            /// The ButtonNext item.
            /// </summary>
            [RepositoryItem("f75a8ed8-e22c-4d8f-8537-fd11578122bf")]
            public virtual Ranorex.Button ButtonNext
            {
                get
                {
                    return _buttonnextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNext item info.
            /// </summary>
            [RepositoryItemInfo("f75a8ed8-e22c-4d8f-8537-fd11578122bf")]
            public virtual RepoItemInfo ButtonNextInfo
            {
                get
                {
                    return _buttonnextInfo;
                }
            }

            /// <summary>
            /// The ButtonFinish item.
            /// </summary>
            [RepositoryItem("17f37782-4773-400d-9dd6-ea1620177f84")]
            public virtual Ranorex.Button ButtonFinish
            {
                get
                {
                    return _buttonfinishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonFinish item info.
            /// </summary>
            [RepositoryItemInfo("17f37782-4773-400d-9dd6-ea1620177f84")]
            public virtual RepoItemInfo ButtonFinishInfo
            {
                get
                {
                    return _buttonfinishInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("a2d3d280-7214-40f3-82a9-55a651fc0849")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("a2d3d280-7214-40f3-82a9-55a651fc0849")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }

            /// <summary>
            /// The ButtonBack item.
            /// </summary>
            [RepositoryItem("4f600f5a-5ca6-4fba-8ed2-2e552135365d")]
            public virtual Ranorex.Button ButtonBack
            {
                get
                {
                    return _buttonbackInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonBack item info.
            /// </summary>
            [RepositoryItemInfo("4f600f5a-5ca6-4fba-8ed2-2e552135365d")]
            public virtual RepoItemInfo ButtonBackInfo
            {
                get
                {
                    return _buttonbackInfo;
                }
            }

            /// <summary>
            /// The Browse item.
            /// </summary>
            [RepositoryItem("2738961d-d45d-43e5-87fb-664e5606cd88")]
            public virtual Ranorex.Button Browse
            {
                get
                {
                    return _browseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Browse item info.
            /// </summary>
            [RepositoryItemInfo("2738961d-d45d-43e5-87fb-664e5606cd88")]
            public virtual RepoItemInfo BrowseInfo
            {
                get
                {
                    return _browseInfo;
                }
            }

            /// <summary>
            /// The DestinationFolder item.
            /// </summary>
            [RepositoryItem("0d1551f6-587a-496f-b412-14766683641b")]
            public virtual Ranorex.Container DestinationFolder
            {
                get
                {
                    return _destinationfolderInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The DestinationFolder item info.
            /// </summary>
            [RepositoryItemInfo("0d1551f6-587a-496f-b412-14766683641b")]
            public virtual RepoItemInfo DestinationFolderInfo
            {
                get
                {
                    return _destinationfolderInfo;
                }
            }

            /// <summary>
            /// The ButtonInstall item.
            /// </summary>
            [RepositoryItem("fd62e641-1c11-427e-b47f-a4dfdd4ea88a")]
            public virtual Ranorex.Button ButtonInstall
            {
                get
                {
                    return _buttoninstallInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonInstall item info.
            /// </summary>
            [RepositoryItemInfo("fd62e641-1c11-427e-b47f-a4dfdd4ea88a")]
            public virtual RepoItemInfo ButtonInstallInfo
            {
                get
                {
                    return _buttoninstallInfo;
                }
            }
        }

        /// <summary>
        /// The UninstallAppAppFolder folder.
        /// </summary>
        [RepositoryFolder("b68af8ab-5363-46b4-b475-56302d974dd2")]
        public partial class UninstallAppAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonnoInfo;
            RepoItemInfo _buttonuninstallInfo;
            RepoItemInfo _buttoncloseInfo;
            RepoItemInfo _progressbarInfo;

            /// <summary>
            /// Creates a new UninstallApp  folder.
            /// </summary>
            public UninstallAppAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UninstallApp", "/form[@title>$repoUninstallApp]", parentFolder, 30000, null, false, "b68af8ab-5363-46b4-b475-56302d974dd2", "")
            {
                _buttonnoInfo = new RepoItemInfo(this, "ButtonNo", "button[@text='&No']", 30000, null, "dda56838-4271-46ce-b4d3-3630dcad2610");
                _buttonuninstallInfo = new RepoItemInfo(this, "ButtonUninstall", "button[@text='&Uninstall']", 30000, null, "4ee6f82f-8c0a-4cbb-a5f0-6c8dc290eb80");
                _buttoncloseInfo = new RepoItemInfo(this, "ButtonClose", "button[@text='&Close']", 30000, null, "a85123db-1353-4217-bff5-5d7d031b113d");
                _progressbarInfo = new RepoItemInfo(this, "ProgressBar", "?/?/progressbar", 30000, null, "fad54f3a-8f97-41b8-9d34-90731dcb28f7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b68af8ab-5363-46b4-b475-56302d974dd2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b68af8ab-5363-46b4-b475-56302d974dd2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonNo item.
            /// </summary>
            [RepositoryItem("dda56838-4271-46ce-b4d3-3630dcad2610")]
            public virtual Ranorex.Button ButtonNo
            {
                get
                {
                    return _buttonnoInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNo item info.
            /// </summary>
            [RepositoryItemInfo("dda56838-4271-46ce-b4d3-3630dcad2610")]
            public virtual RepoItemInfo ButtonNoInfo
            {
                get
                {
                    return _buttonnoInfo;
                }
            }

            /// <summary>
            /// The ButtonUninstall item.
            /// </summary>
            [RepositoryItem("4ee6f82f-8c0a-4cbb-a5f0-6c8dc290eb80")]
            public virtual Ranorex.Button ButtonUninstall
            {
                get
                {
                    return _buttonuninstallInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonUninstall item info.
            /// </summary>
            [RepositoryItemInfo("4ee6f82f-8c0a-4cbb-a5f0-6c8dc290eb80")]
            public virtual RepoItemInfo ButtonUninstallInfo
            {
                get
                {
                    return _buttonuninstallInfo;
                }
            }

            /// <summary>
            /// The ButtonClose item.
            /// </summary>
            [RepositoryItem("a85123db-1353-4217-bff5-5d7d031b113d")]
            public virtual Ranorex.Button ButtonClose
            {
                get
                {
                    return _buttoncloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonClose item info.
            /// </summary>
            [RepositoryItemInfo("a85123db-1353-4217-bff5-5d7d031b113d")]
            public virtual RepoItemInfo ButtonCloseInfo
            {
                get
                {
                    return _buttoncloseInfo;
                }
            }

            /// <summary>
            /// The ProgressBar item.
            /// </summary>
            [RepositoryItem("fad54f3a-8f97-41b8-9d34-90731dcb28f7")]
            public virtual Ranorex.ProgressBar ProgressBar
            {
                get
                {
                    return _progressbarInfo.CreateAdapter<Ranorex.ProgressBar>(true);
                }
            }

            /// <summary>
            /// The ProgressBar item info.
            /// </summary>
            [RepositoryItemInfo("fad54f3a-8f97-41b8-9d34-90731dcb28f7")]
            public virtual RepoItemInfo ProgressBarInfo
            {
                get
                {
                    return _progressbarInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("7d3fb789-93fd-4f24-b21b-1d4a9e55c998")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _typeheretosearchInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "7d3fb789-93fd-4f24-b21b-1d4a9e55c998", "")
            {
                _typeheretosearchInfo = new RepoItemInfo(this, "TypeHereToSearch", "?/?/button[@controlid='4101']", 30000, null, "dab67e7e-2827-4322-9197-65a77711b1b0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7d3fb789-93fd-4f24-b21b-1d4a9e55c998")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7d3fb789-93fd-4f24-b21b-1d4a9e55c998")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TypeHereToSearch item.
            /// </summary>
            [RepositoryItem("dab67e7e-2827-4322-9197-65a77711b1b0")]
            public virtual Ranorex.Button TypeHereToSearch
            {
                get
                {
                    return _typeheretosearchInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The TypeHereToSearch item info.
            /// </summary>
            [RepositoryItemInfo("dab67e7e-2827-4322-9197-65a77711b1b0")]
            public virtual RepoItemInfo TypeHereToSearchInfo
            {
                get
                {
                    return _typeheretosearchInfo;
                }
            }
        }

        /// <summary>
        /// The ControlPanelAppFolder folder.
        /// </summary>
        [RepositoryFolder("85df6248-2b37-4e80-bf55-340192a87131")]
        public partial class ControlPanelAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tasklinkInfo;

            /// <summary>
            /// Creates a new ControlPanel  folder.
            /// </summary>
            public ControlPanelAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ControlPanel", "/form[@title='Control Panel']", parentFolder, 30000, null, true, "85df6248-2b37-4e80-bf55-340192a87131", "")
            {
                _tasklinkInfo = new RepoItemInfo(this, "Tasklink", ".//container[@automationid='FolderLayoutContainer']/container[@automationid='CategoryPanel']/link[@name='Uninstall a program']", 30000, null, "01ac394c-a5e7-4a75-a56e-ebc2b8c08a84");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("85df6248-2b37-4e80-bf55-340192a87131")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("85df6248-2b37-4e80-bf55-340192a87131")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tasklink item.
            /// </summary>
            [RepositoryItem("01ac394c-a5e7-4a75-a56e-ebc2b8c08a84")]
            public virtual Ranorex.Link Tasklink
            {
                get
                {
                    return _tasklinkInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The Tasklink item info.
            /// </summary>
            [RepositoryItemInfo("01ac394c-a5e7-4a75-a56e-ebc2b8c08a84")]
            public virtual RepoItemInfo TasklinkInfo
            {
                get
                {
                    return _tasklinkInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
