///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Web_Dashboard_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Web_Dashboard_TestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("d741e25a-b2c1-41c9-a3bd-786e581fcfb1")]
    public partial class Web_Dashboard_TestRepository : RepoGenBaseFolder
    {
        static Web_Dashboard_TestRepository instance = new Web_Dashboard_TestRepository();

        /// <summary>
        /// Gets the singleton class instance representing the Web_Dashboard_TestRepository element repository.
        /// </summary>
        [RepositoryFolder("d741e25a-b2c1-41c9-a3bd-786e581fcfb1")]
        public static Web_Dashboard_TestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Web_Dashboard_TestRepository() 
            : base("Web_Dashboard_TestRepository", "/", null, 0, false, "d741e25a-b2c1-41c9-a3bd-786e581fcfb1", ".\\RepositoryImages\\Web_Dashboard_TestRepositoryd741e25a.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d741e25a-b2c1-41c9-a3bd-786e581fcfb1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Web_Dashboard_TestRepositoryFolders
    {
    }
#pragma warning restore 0436
}
