///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Web_DashBoard.Record_Actions.Common
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GenerateUpdateName recording.
    /// </summary>
    [TestModule("68c8aa2f-900e-4f76-b2b1-02fefaf1e51f", ModuleType.Recording, 1)]
    public partial class GenerateUpdateName : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Web_DashBoard.Web_DashBoardRepository repository.
        /// </summary>
        public static global::Web_DashBoard.Web_DashBoardRepository repo = global::Web_DashBoard.Web_DashBoardRepository.Instance;

        static GenerateUpdateName instance = new GenerateUpdateName();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GenerateUpdateName()
        {
            modUpdatedName = "";
            modUpdateName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GenerateUpdateName Instance
        {
            get { return instance; }
        }

#region Variables

        string _modUpdatedName;

        /// <summary>
        /// Gets or sets the value of variable modUpdatedName.
        /// </summary>
        [TestVariable("150112c1-739c-4393-8b80-96cb0c0a9b0f")]
        public string modUpdatedName
        {
            get { return _modUpdatedName; }
            set { _modUpdatedName = value; }
        }

        string _modUpdateName;

        /// <summary>
        /// Gets or sets the value of variable modUpdateName.
        /// </summary>
        [TestVariable("662328e7-5c21-4284-b51b-8fa2ef5646a6")]
        public string modUpdateName
        {
            get { return _modUpdateName; }
            set { _modUpdateName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            modUpdatedName = GetUpdatedName(modUpdateName);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
