///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DesktopApp_Modules.ApplicationModules.Chrome
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DownloadApp recording.
    /// </summary>
    [TestModule("1079f995-3537-470e-a785-773b49ffa279", ModuleType.Recording, 1)]
    public partial class DownloadApp : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DesktopApp_Modules.DesktopApp_ModulesRepository repository.
        /// </summary>
        public static global::DesktopApp_Modules.DesktopApp_ModulesRepository repo = global::DesktopApp_Modules.DesktopApp_ModulesRepository.Instance;

        static DownloadApp instance = new DownloadApp();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DownloadApp()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DownloadApp Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DownloadsNotepadPlusPlus.ATagNotepadPlusPlus786R' at 150;11.", repo.DownloadsNotepadPlusPlus.ATagNotepadPlusPlus786RInfo, new RecordItemIndex(0));
            repo.DownloadsNotepadPlusPlus.ATagNotepadPlusPlus786R.Click("150;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DownloadsNotepadPlusPlus.Installer' at Center.", repo.DownloadsNotepadPlusPlus.InstallerInfo, new RecordItemIndex(1));
            repo.DownloadsNotepadPlusPlus.Installer.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1.7m to exist. Associated repository item: 'NotepadPlusPlus786ReleaseNotepadP.ButtonNpp786InstallerX646Exe'", repo.NotepadPlusPlus786ReleaseNotepadP.ButtonNpp786InstallerX646ExeInfo, new ActionTimeout(100000), new RecordItemIndex(2));
            repo.NotepadPlusPlus786ReleaseNotepadP.ButtonNpp786InstallerX646ExeInfo.WaitForExists(100000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
