///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DesktopApp_Modules.ApplicationModules.Chrome
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DownloadApp recording.
    /// </summary>
    [TestModule("1079f995-3537-470e-a785-773b49ffa279", ModuleType.Recording, 1)]
    public partial class DownloadApp : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DesktopApp_Modules.DesktopApp_ModulesRepository repository.
        /// </summary>
        public static global::DesktopApp_Modules.DesktopApp_ModulesRepository repo = global::DesktopApp_Modules.DesktopApp_ModulesRepository.Instance;

        static DownloadApp instance = new DownloadApp();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DownloadApp()
        {
            repoVersionApp = "7.8.6";
            repoWindownVersion = "64";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DownloadApp Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable repoWindownVersion.
        /// </summary>
        [TestVariable("f8d32d52-e8bd-4c90-b774-55f6418a93c6")]
        public string repoWindownVersion
        {
            get { return repo.repoWindownVersion; }
            set { repo.repoWindownVersion = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable repoVersionApp.
        /// </summary>
        [TestVariable("c33a7b58-c069-4176-98d7-9637f83d8b63")]
        public string repoVersionApp
        {
            get { return repo.repoVersionApp; }
            set { repo.repoVersionApp = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationModules.Browser.DownloadsNotepadPlusPlus.ATagNotepadPlusPlus786R' at 24;16.", repo.ApplicationModules.Browser.DownloadsNotepadPlusPlus.ATagNotepadPlusPlus786RInfo, new RecordItemIndex(0));
            repo.ApplicationModules.Browser.DownloadsNotepadPlusPlus.ATagNotepadPlusPlus786R.Click("24;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationModules.Browser.DownloadsNotepadPlusPlus.Installer' at Center.", repo.ApplicationModules.Browser.DownloadsNotepadPlusPlus.InstallerInfo, new RecordItemIndex(1));
            repo.ApplicationModules.Browser.DownloadsNotepadPlusPlus.Installer.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", repoVersionApp, new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "User", repoWindownVersion, new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5m to exist. Associated repository item: 'ApplicationModules.Browser.NotepadPlusPlus786ReleaseNotepadP.ButtonNpp786InstallerX646Exe'", repo.ApplicationModules.Browser.NotepadPlusPlus786ReleaseNotepadP.ButtonNpp786InstallerX646ExeInfo, new ActionTimeout(300000), new RecordItemIndex(4));
            repo.ApplicationModules.Browser.NotepadPlusPlus786ReleaseNotepadP.ButtonNpp786InstallerX646ExeInfo.WaitForExists(300000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
