///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DesktopApp_Modules.ApplicationModules.Chrome
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateDownloaded recording.
    /// </summary>
    [TestModule("9a097a65-4066-42c4-9816-9c541e035607", ModuleType.Recording, 1)]
    public partial class ValidateDownloaded : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DesktopApp_Modules.DesktopApp_ModulesRepository repository.
        /// </summary>
        public static global::DesktopApp_Modules.DesktopApp_ModulesRepository repo = global::DesktopApp_Modules.DesktopApp_ModulesRepository.Instance;

        static ValidateDownloaded instance = new ValidateDownloaded();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateDownloaded()
        {
            varFileSetupName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateDownloaded Instance
        {
            get { return instance; }
        }

#region Variables

        string _varFileSetupName;

        /// <summary>
        /// Gets or sets the value of variable varFileSetupName.
        /// </summary>
        [TestVariable("2a7bc221-2d79-4cb4-80e1-a85d20d7adb9")]
        public string varFileSetupName
        {
            get { return _varFileSetupName; }
            set { _varFileSetupName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable repoVersionApp.
        /// </summary>
        [TestVariable("c33a7b58-c069-4176-98d7-9637f83d8b63")]
        public string repoVersionApp
        {
            get { return repo.repoVersionApp; }
            set { repo.repoVersionApp = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>$varFileSetupName) on item 'ApplicationModules.Browser.NotepadPlusPlus786ReleaseNotepadP.ButtonNpp786InstallerX646Exe'.", repo.ApplicationModules.Browser.NotepadPlusPlus786ReleaseNotepadP.ButtonNpp786InstallerX646ExeInfo, new RecordItemIndex(0));
            Validate.AttributeContains(repo.ApplicationModules.Browser.NotepadPlusPlus786ReleaseNotepadP.ButtonNpp786InstallerX646ExeInfo, "Text", varFileSetupName);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
